# Generated by Django 6.0.3 on 2026-09-22 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Hotel Name')),
                ('location', models.CharField(max_length=255, verbose_name='City / Area Location')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=3, verbose_name='Rating')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price Per Night (NPR)')),
                ('amenities', models.JSONField(blank=True, default=list, verbose_name='Amenities')),
                ('image', models.CharField(blank=True, default='', max_length=500, verbose_name='Image URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
                'db_table': 'hotels',
                'ordering': ['-rating', 'price_per_night'],
            },
        ),
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('check_in', models.DateField(verbose_name='Check In Date')),
                ('check_out', models.DateField(verbose_name='Check Out Date')),
                ('guests', models.PositiveIntegerField(default=1, verbose_name='Guests Count')),
                ('rooms', models.PositiveIntegerField(default=1, verbose_name='Rooms Count')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=30, verbose_name='Booking Status')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Amount (NPR)')),
                ('special_requests', models.TextField(blank=True, default='', verbose_name='Special Requests')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotels.hotel', verbose_name='Hotel')),
            ],
            options={
                'verbose_name': 'Hotel Booking',
                'verbose_name_plural': 'Hotel Bookings',
                'db_table': 'hotel_bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
