# Generated by Django 6.0.3 on 2026-09-22 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaApplication',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100, verbose_name='Destination Country')),
                ('visa_type', models.CharField(choices=[('TOURIST', 'Tourist'), ('WORK', 'Work'), ('BUSINESS', 'Business'), ('STUDENT', 'Student')], default='TOURIST', max_length=30, verbose_name='Visa Type')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name as in Passport')),
                ('phone', models.CharField(max_length=30, verbose_name='Contact Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('passport_number', models.CharField(max_length=50, verbose_name='Passport Number')),
                ('travel_date', models.DateField(verbose_name='Expected Travel Date')),
                ('nationality', models.CharField(default='Nepalese', max_length=100, verbose_name='Nationality')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('DOCUMENT_REQUIRED', 'Document Required'), ('PROCESSING', 'Processing'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='SUBMITTED', max_length=30, verbose_name='Application Status')),
                ('admin_notes', models.TextField(blank=True, default='', verbose_name='Admin Notes')),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='Rejection Reason')),
                ('government_fee_npr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Government / Processing Fee (NPR)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_applications', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Visa Application',
                'verbose_name_plural': 'Visa Applications',
                'db_table': 'visa_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisaDocument',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(default='PASSPORT', max_length=100, verbose_name='Document Type')),
                ('file', models.FileField(upload_to='visa_documents/%Y/%m/', verbose_name='Document File')),
                ('file_name', models.CharField(max_length=255, verbose_name='Original File Name')),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes', verbose_name='File Size (Bytes)')),
                ('mime_type', models.CharField(blank=True, default='', max_length=100, verbose_name='MIME Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='visas.visaapplication', verbose_name='Visa Application')),
            ],
            options={
                'verbose_name': 'Visa Document',
                'verbose_name_plural': 'Visa Documents',
                'db_table': 'visa_documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
