# Generated by Django 6.0.3 on 2026-09-22 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trip_type', models.CharField(choices=[('ONE_WAY', 'One Way'), ('ROUND_TRIP', 'Round Trip')], default='ONE_WAY', max_length=20, verbose_name='Trip Type')),
                ('from_location', models.CharField(max_length=255, verbose_name='From Location')),
                ('to_location', models.CharField(max_length=255, verbose_name='To Location')),
                ('departure_date', models.DateField(verbose_name='Departure Date')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Return Date')),
                ('adults', models.PositiveIntegerField(default=1, verbose_name='Adults')),
                ('children', models.PositiveIntegerField(default=0, verbose_name='Children')),
                ('travel_class', models.CharField(choices=[('ECONOMY', 'Economy'), ('PREMIUM_ECONOMY', 'Premium Economy'), ('BUSINESS', 'Business'), ('FIRST', 'First')], default='ECONOMY', max_length=30, verbose_name='Travel Class')),
                ('special_request', models.TextField(blank=True, default='', verbose_name='Special Request')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('QUOTATION_SENT', 'Quotation Sent'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=30, verbose_name='Status')),
                ('admin_notes', models.TextField(blank=True, default='', verbose_name='Admin Notes')),
                ('quotation_amount_npr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Quotation Amount (NPR)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_requests', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Ticket Request',
                'verbose_name_plural': 'Ticket Requests',
                'db_table': 'ticket_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
