# Generated by Django 6.0.3 on 2026-10-02 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightAuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=50, verbose_name='Event Type')),
                ('booking_reference', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Booking Reference')),
                ('pnr', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='PNR')),
                ('details', models.JSONField(default=dict, verbose_name='Details')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
            ],
            options={
                'verbose_name': 'Flight Audit Log',
                'verbose_name_plural': 'Flight Audit Logs',
                'db_table': 'flight_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlightBooking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(default='TRAVELPORT', max_length=50, verbose_name='GDS Provider')),
                ('provider_booking_reference', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Provider Booking Reference')),
                ('pnr', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Airline PNR / Record Locator')),
                ('status', models.CharField(choices=[('PAYMENT_PENDING', 'Payment Pending'), ('PAYMENT_SUCCESS', 'Payment Success'), ('BOOKING_IN_PROGRESS', 'Booking In Progress'), ('BOOKED', 'Booked'), ('TICKETING_IN_PROGRESS', 'Ticketing In Progress'), ('TICKETED', 'Ticketed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUND_PENDING', 'Refund Pending'), ('REFUNDED', 'Refunded')], db_index=True, default='PAYMENT_PENDING', max_length=30, verbose_name='Booking Status')),
                ('currency', models.CharField(default='NPR', max_length=10, verbose_name='Currency')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Amount')),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='Idempotency Key')),
                ('origin', models.CharField(max_length=100, verbose_name='Origin')),
                ('destination', models.CharField(max_length=100, verbose_name='Destination')),
                ('departure_date', models.DateField(db_index=True, verbose_name='Departure Date')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Return Date')),
                ('cabin_class', models.CharField(default='ECONOMY', max_length=30, verbose_name='Cabin Class')),
                ('fare_tier', models.CharField(default='STANDARD', max_length=30, verbose_name='Fare Tier')),
                ('special_requests', models.TextField(blank=True, default='', verbose_name='Special Requests')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Flight Booking',
                'verbose_name_plural': 'Flight Bookings',
                'db_table': 'flight_bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlightPassenger',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('passenger_type', models.CharField(choices=[('ADULT', 'Adult'), ('CHILD', 'Child'), ('INFANT', 'Infant')], default='ADULT', max_length=20, verbose_name='Passenger Type')),
                ('title', models.CharField(default='MR', max_length=10, verbose_name='Title')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='MALE', max_length=10)),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('nationality', models.CharField(default='Nepal', max_length=50, verbose_name='Nationality')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Phone')),
                ('document_type', models.CharField(default='PASSPORT', max_length=30, verbose_name='Document Type')),
                ('passport_number', models.CharField(blank=True, default='', max_length=50, verbose_name='Passport / ID Number')),
                ('passport_expiry_date', models.DateField(blank=True, null=True, verbose_name='Passport Expiry Date')),
                ('passport_issuing_country', models.CharField(blank=True, default='Nepal', max_length=50, verbose_name='Issuing Country')),
                ('meal_preference', models.CharField(blank=True, default='STANDARD', max_length=30, verbose_name='Meal Preference')),
                ('special_assistance', models.CharField(blank=True, default='NONE', max_length=30, verbose_name='Special Assistance')),
                ('seat_number', models.CharField(blank=True, default='', max_length=10, verbose_name='Seat Number')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='tickets.flightbooking', verbose_name='Booking')),
            ],
            options={
                'verbose_name': 'Flight Passenger',
                'verbose_name_plural': 'Flight Passengers',
                'db_table': 'flight_passengers',
            },
        ),
        migrations.CreateModel(
            name='FlightPayment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('currency', models.CharField(default='NPR', max_length=10, verbose_name='Currency')),
                ('provider', models.CharField(default='ESEWA', max_length=50, verbose_name='Payment Provider')),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Provider Reference')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20, verbose_name='Payment Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tickets.flightbooking', verbose_name='Booking')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_payments', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Flight Payment',
                'verbose_name_plural': 'Flight Payments',
                'db_table': 'flight_payments',
            },
        ),
        migrations.CreateModel(
            name='FlightSegment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('airline_code', models.CharField(max_length=10, verbose_name='Airline Code')),
                ('airline_name', models.CharField(max_length=100, verbose_name='Airline Name')),
                ('flight_number', models.CharField(max_length=20, verbose_name='Flight Number')),
                ('origin', models.CharField(max_length=100, verbose_name='Origin')),
                ('destination', models.CharField(max_length=100, verbose_name='Destination')),
                ('departure_time', models.CharField(max_length=50, verbose_name='Departure Time')),
                ('arrival_time', models.CharField(max_length=50, verbose_name='Arrival Time')),
                ('duration', models.CharField(default='4h 30m', max_length=30, verbose_name='Duration')),
                ('stops', models.PositiveIntegerField(default=0, verbose_name='Stops')),
                ('cabin_class', models.CharField(default='ECONOMY', max_length=30, verbose_name='Cabin Class')),
                ('baggage_allowance', models.CharField(default='30 kg Check-in + 7 kg Cabin', max_length=100, verbose_name='Baggage Allowance')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='tickets.flightbooking', verbose_name='Booking')),
            ],
            options={
                'verbose_name': 'Flight Segment',
                'verbose_name_plural': 'Flight Segments',
                'db_table': 'flight_segments',
            },
        ),
        migrations.CreateModel(
            name='FlightTicket',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='E-Ticket Number (13-Digit)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ISSUED', 'Issued'), ('FAILED', 'Failed'), ('VOIDED', 'Voided'), ('REFUNDED', 'Refunded')], default='ISSUED', max_length=20, verbose_name='Ticket Status')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='Issued At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.flightbooking', verbose_name='Booking')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.flightpassenger', verbose_name='Passenger')),
            ],
            options={
                'verbose_name': 'Flight Ticket',
                'verbose_name_plural': 'Flight Tickets',
                'db_table': 'flight_tickets',
            },
        ),
    ]
